name: "Install dependencies"
description: "Prepare repository and all dependencies"

inputs:
  skip-cache:
    description: 'Skip dependency cache restore/save'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Set up pnpm
      uses: wevm/actions/.github/actions/pnpm@f95dc1dadcba18fe3f02b8205e653e98e4a93516
      with:
        node-version: 24.5
        skip-cache: ${{ inputs.skip-cache }}
