packages:
  - site

catalog:
  '@types/react': ^19
  '@types/react-dom': ^19
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: 5.9.3

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@modelcontextprotocol/sdk'
  - abitype
  - fastify
  - glob
  - hono
  - lodash
  - lodash-es
  - ox
  - prool
  - qs
  - tar
  - vocs
  - webpack
  - basic-ftp
