auditConfig:
  ignoreGhsas:
    - GHSA-ffrw-9mx8-89p8
    - GHSA-mh29-5h37-fv8m
catalog:
  '@types/react': ^19
  '@types/react-dom': ^19
  react: ^19
  react-dom: ^19
  typescript: 5.9.2
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@vitest/*'
  - glob  
  - hono
  - ox
  - prool
  - vitest
  - vocs
packages:
  - examples/*
  - environments/*
  - site
  - src
  - test
