packages:
  - site

catalog:
  '@types/react': ^19
  '@types/react-dom': ^19
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^6.0.3

minimumReleaseAge: 1440

overrides:
  'permissionless>viem': 'workspace:*'
