// deno-fmt-ignore-file
// biome-ignore format: generated types do not need formatting
// prettier-ignore
import type { PathsForPages, GetConfigResponse } from 'waku/router';


// prettier-ignore
type Page =
| { path: '/account-abstraction'; render: 'static' }
| { path: '/circle-usdc'; render: 'static' }
| { path: '/experimental'; render: 'static' }
| { path: '/'; render: 'static' }
| { path: '/op-stack'; render: 'static' }
| { path: '/zksync'; render: 'static' }
| { path: '/zksync/chains'; render: 'static' }
| { path: '/zksync/client'; render: 'static' }
| { path: '/zksync/utilities/parseEip712Transaction'; render: 'static' }
| { path: '/zksync/utilities/paymaster/getApprovalBasedPaymasterInput'; render: 'static' }
| { path: '/zksync/utilities/paymaster/getGeneralPaymasterInput'; render: 'static' }
| { path: '/zksync/utilities/bridge/getL2HashFromPriorityOp'; render: 'static' }
| { path: '/zksync/actions/claimFailedDeposit'; render: 'static' }
| { path: '/zksync/actions/deployContract'; render: 'static' }
| { path: '/zksync/actions/deposit'; render: 'static' }
| { path: '/zksync/actions/estimateFee'; render: 'static' }
| { path: '/zksync/actions/estimateGasL1ToL2'; render: 'static' }
| { path: '/zksync/actions/finalizeWithdrawal'; render: 'static' }
| { path: '/zksync/actions/getAllBalances'; render: 'static' }
| { path: '/zksync/actions/getBaseTokenL1Address'; render: 'static' }
| { path: '/zksync/actions/getBlockDetails'; render: 'static' }
| { path: '/zksync/actions/getBridgehubContractAddress'; render: 'static' }
| { path: '/zksync/actions/getDefaultBridgeAddress'; render: 'static' }
| { path: '/zksync/actions/getGasPerPubData'; render: 'static' }
| { path: '/zksync/actions/getL1Allowance'; render: 'static' }
| { path: '/zksync/actions/getL1Balance'; render: 'static' }
| { path: '/zksync/actions/getL1BatchBlockRange'; render: 'static' }
| { path: '/zksync/actions/getL1BatchDetails'; render: 'static' }
| { path: '/zksync/actions/getL1BatchNumber'; render: 'static' }
| { path: '/zksync/actions/getL1ChainId'; render: 'static' }
| { path: '/zksync/actions/getL1TokenAddress'; render: 'static' }
| { path: '/zksync/actions/getL1TokenBalance'; render: 'static' }
| { path: '/zksync/actions/getL2TokenAddress'; render: 'static' }
| { path: '/zksync/actions/getLogProof'; render: 'static' }
| { path: '/zksync/actions/getMainContractAddress'; render: 'static' }
| { path: '/zksync/actions/getRawBlockTransactions'; render: 'static' }
| { path: '/zksync/actions/getTestnetPaymasterAddress'; render: 'static' }
| { path: '/zksync/actions/getTransactionDetails'; render: 'static' }
| { path: '/zksync/actions/isWithdrawalFinalized'; render: 'static' }
| { path: '/zksync/actions/requestExecute'; render: 'static' }
| { path: '/zksync/actions/sendTransaction'; render: 'static' }
| { path: '/zksync/actions/signTransaction'; render: 'static' }
| { path: '/zksync/actions/withdraw'; render: 'static' }
| { path: '/zksync/actions/writeContract'; render: 'static' }
| { path: '/zksync/accounts/toMultisigSmartAccount'; render: 'static' }
| { path: '/zksync/accounts/toSinglesigSmartAccount'; render: 'static' }
| { path: '/zksync/accounts/toSmartAccount'; render: 'static' }
| { path: '/tempo/chains'; render: 'static' }
| { path: '/tempo'; render: 'static' }
| { path: '/tempo/transactions'; render: 'static' }
| { path: '/tempo/transports/withFeePayer'; render: 'static' }
| { path: '/tempo/actions/amm.burn'; render: 'static' }
| { path: '/tempo/actions/amm.getLiquidityBalance'; render: 'static' }
| { path: '/tempo/actions/amm.getPool'; render: 'static' }
| { path: '/tempo/actions/amm.mint'; render: 'static' }
| { path: '/tempo/actions/amm.rebalanceSwap'; render: 'static' }
| { path: '/tempo/actions/amm.watchBurn'; render: 'static' }
| { path: '/tempo/actions/amm.watchMint'; render: 'static' }
| { path: '/tempo/actions/amm.watchRebalanceSwap'; render: 'static' }
| { path: '/tempo/actions/dex.buy'; render: 'static' }
| { path: '/tempo/actions/dex.cancel'; render: 'static' }
| { path: '/tempo/actions/dex.cancelStale'; render: 'static' }
| { path: '/tempo/actions/dex.createPair'; render: 'static' }
| { path: '/tempo/actions/dex.getBalance'; render: 'static' }
| { path: '/tempo/actions/dex.getBuyQuote'; render: 'static' }
| { path: '/tempo/actions/dex.getOrder'; render: 'static' }
| { path: '/tempo/actions/dex.getSellQuote'; render: 'static' }
| { path: '/tempo/actions/dex.getTickLevel'; render: 'static' }
| { path: '/tempo/actions/dex.place'; render: 'static' }
| { path: '/tempo/actions/dex.placeFlip'; render: 'static' }
| { path: '/tempo/actions/dex.sell'; render: 'static' }
| { path: '/tempo/actions/dex.watchFlipOrderPlaced'; render: 'static' }
| { path: '/tempo/actions/dex.watchOrderCancelled'; render: 'static' }
| { path: '/tempo/actions/dex.watchOrderFilled'; render: 'static' }
| { path: '/tempo/actions/dex.watchOrderPlaced'; render: 'static' }
| { path: '/tempo/actions/dex.withdraw'; render: 'static' }
| { path: '/tempo/actions/faucet.fund'; render: 'static' }
| { path: '/tempo/actions/fee.getUserToken'; render: 'static' }
| { path: '/tempo/actions/fee.setUserToken'; render: 'static' }
| { path: '/tempo/actions/fee.watchSetUserToken'; render: 'static' }
| { path: '/tempo/actions'; render: 'static' }
| { path: '/tempo/actions/nonce.getNonce'; render: 'static' }
| { path: '/tempo/actions/nonce.watchNonceIncremented'; render: 'static' }
| { path: '/tempo/actions/policy.create'; render: 'static' }
| { path: '/tempo/actions/policy.getData'; render: 'static' }
| { path: '/tempo/actions/policy.isAuthorized'; render: 'static' }
| { path: '/tempo/actions/policy.modifyBlacklist'; render: 'static' }
| { path: '/tempo/actions/policy.modifyWhitelist'; render: 'static' }
| { path: '/tempo/actions/policy.setAdmin'; render: 'static' }
| { path: '/tempo/actions/policy.watchAdminUpdated'; render: 'static' }
| { path: '/tempo/actions/policy.watchBlacklistUpdated'; render: 'static' }
| { path: '/tempo/actions/policy.watchCreate'; render: 'static' }
| { path: '/tempo/actions/policy.watchWhitelistUpdated'; render: 'static' }
| { path: '/tempo/actions/reward.claim'; render: 'static' }
| { path: '/tempo/actions/reward.distribute'; render: 'static' }
| { path: '/tempo/actions/reward.getGlobalRewardPerToken'; render: 'static' }
| { path: '/tempo/actions/reward.getPendingRewards'; render: 'static' }
| { path: '/tempo/actions/reward.getUserRewardInfo'; render: 'static' }
| { path: '/tempo/actions/reward.setRecipient'; render: 'static' }
| { path: '/tempo/actions/reward.watchRewardDistributed'; render: 'static' }
| { path: '/tempo/actions/reward.watchRewardRecipientSet'; render: 'static' }
| { path: '/tempo/actions/setup'; render: 'static' }
| { path: '/tempo/actions/token.approve'; render: 'static' }
| { path: '/tempo/actions/token.burn'; render: 'static' }
| { path: '/tempo/actions/token.burnBlocked'; render: 'static' }
| { path: '/tempo/actions/token.changeTransferPolicy'; render: 'static' }
| { path: '/tempo/actions/token.create'; render: 'static' }
| { path: '/tempo/actions/token.getAllowance'; render: 'static' }
| { path: '/tempo/actions/token.getBalance'; render: 'static' }
| { path: '/tempo/actions/token.getMetadata'; render: 'static' }
| { path: '/tempo/actions/token.grantRoles'; render: 'static' }
| { path: '/tempo/actions/token.hasRole'; render: 'static' }
| { path: '/tempo/actions/token.mint'; render: 'static' }
| { path: '/tempo/actions/token.pause'; render: 'static' }
| { path: '/tempo/actions/token.renounceRoles'; render: 'static' }
| { path: '/tempo/actions/token.revokeRoles'; render: 'static' }
| { path: '/tempo/actions/token.setRoleAdmin'; render: 'static' }
| { path: '/tempo/actions/token.setSupplyCap'; render: 'static' }
| { path: '/tempo/actions/token.transfer'; render: 'static' }
| { path: '/tempo/actions/token.unpause'; render: 'static' }
| { path: '/tempo/actions/token.watchAdminRole'; render: 'static' }
| { path: '/tempo/actions/token.watchApprove'; render: 'static' }
| { path: '/tempo/actions/token.watchBurn'; render: 'static' }
| { path: '/tempo/actions/token.watchCreate'; render: 'static' }
| { path: '/tempo/actions/token.watchMint'; render: 'static' }
| { path: '/tempo/actions/token.watchRole'; render: 'static' }
| { path: '/tempo/actions/token.watchTransfer'; render: 'static' }
| { path: '/tempo/actions/validator.add'; render: 'static' }
| { path: '/tempo/actions/validator.changeOwner'; render: 'static' }
| { path: '/tempo/actions/validator.changeStatus'; render: 'static' }
| { path: '/tempo/actions/validator.get'; render: 'static' }
| { path: '/tempo/actions/validator.getByIndex'; render: 'static' }
| { path: '/tempo/actions/validator.getCount'; render: 'static' }
| { path: '/tempo/actions/validator.getNextFullDkgCeremony'; render: 'static' }
| { path: '/tempo/actions/validator.getOwner'; render: 'static' }
| { path: '/tempo/actions/validator.list'; render: 'static' }
| { path: '/tempo/actions/validator.setNextFullDkgCeremony'; render: 'static' }
| { path: '/tempo/actions/validator.update'; render: 'static' }
| { path: '/tempo/accounts/account.fromP256'; render: 'static' }
| { path: '/tempo/accounts/account.fromSecp256k1'; render: 'static' }
| { path: '/tempo/accounts/account.fromWebAuthnP256'; render: 'static' }
| { path: '/tempo/accounts/account.fromWebCryptoP256'; render: 'static' }
| { path: '/tempo/accounts'; render: 'static' }
| { path: '/op-stack/chains'; render: 'static' }
| { path: '/op-stack/client'; render: 'static' }
| { path: '/op-stack/utilities/extractTransactionDepositedLogs'; render: 'static' }
| { path: '/op-stack/utilities/extractWithdrawalMessageLogs'; render: 'static' }
| { path: '/op-stack/utilities/fromOpaqueData'; render: 'static' }
| { path: '/op-stack/utilities/getL2TransactionHash'; render: 'static' }
| { path: '/op-stack/utilities/getL2TransactionHashes'; render: 'static' }
| { path: '/op-stack/utilities/getSourceHash'; render: 'static' }
| { path: '/op-stack/utilities/getWithdrawalHashStorageSlot'; render: 'static' }
| { path: '/op-stack/utilities/getWithdrawals'; render: 'static' }
| { path: '/op-stack/utilities/opaqueDataToDepositData'; render: 'static' }
| { path: '/op-stack/utilities/parseTransaction'; render: 'static' }
| { path: '/op-stack/utilities/serializeTransaction'; render: 'static' }
| { path: '/op-stack/guides/deposits'; render: 'static' }
| { path: '/op-stack/guides/withdrawals'; render: 'static' }
| { path: '/op-stack/actions/buildDepositTransaction'; render: 'static' }
| { path: '/op-stack/actions/buildInitiateWithdrawal'; render: 'static' }
| { path: '/op-stack/actions/buildProveWithdrawal'; render: 'static' }
| { path: '/op-stack/actions/depositTransaction'; render: 'static' }
| { path: '/op-stack/actions/estimateContractL1Fee'; render: 'static' }
| { path: '/op-stack/actions/estimateContractL1Gas'; render: 'static' }
| { path: '/op-stack/actions/estimateContractTotalFee'; render: 'static' }
| { path: '/op-stack/actions/estimateContractTotalGas'; render: 'static' }
| { path: '/op-stack/actions/estimateDepositTransactionGas'; render: 'static' }
| { path: '/op-stack/actions/estimateFinalizeWithdrawalGas'; render: 'static' }
| { path: '/op-stack/actions/estimateInitiateWithdrawalGas'; render: 'static' }
| { path: '/op-stack/actions/estimateL1Fee'; render: 'static' }
| { path: '/op-stack/actions/estimateL1Gas'; render: 'static' }
| { path: '/op-stack/actions/estimateOperatorFee'; render: 'static' }
| { path: '/op-stack/actions/estimateProveWithdrawalGas'; render: 'static' }
| { path: '/op-stack/actions/estimateTotalFee'; render: 'static' }
| { path: '/op-stack/actions/estimateTotalGas'; render: 'static' }
| { path: '/op-stack/actions/finalizeWithdrawal'; render: 'static' }
| { path: '/op-stack/actions/getGame'; render: 'static' }
| { path: '/op-stack/actions/getGames'; render: 'static' }
| { path: '/op-stack/actions/getL2Output'; render: 'static' }
| { path: '/op-stack/actions/getTimeToFinalize'; render: 'static' }
| { path: '/op-stack/actions/getTimeToNextGame'; render: 'static' }
| { path: '/op-stack/actions/getTimeToNextL2Output'; render: 'static' }
| { path: '/op-stack/actions/getTimeToProve'; render: 'static' }
| { path: '/op-stack/actions/getWithdrawalStatus'; render: 'static' }
| { path: '/op-stack/actions/initiateWithdrawal'; render: 'static' }
| { path: '/op-stack/actions/proveWithdrawal'; render: 'static' }
| { path: '/op-stack/actions/waitForNextGame'; render: 'static' }
| { path: '/op-stack/actions/waitForNextL2Output'; render: 'static' }
| { path: '/op-stack/actions/waitToFinalize'; render: 'static' }
| { path: '/op-stack/actions/waitToProve'; render: 'static' }
| { path: '/experimental/client'; render: 'static' }
| { path: '/experimental/erc7895/addSubAccount'; render: 'static' }
| { path: '/experimental/erc7895/client'; render: 'static' }
| { path: '/experimental/erc7846/client'; render: 'static' }
| { path: '/experimental/erc7846/connect'; render: 'static' }
| { path: '/experimental/erc7846/disconnect'; render: 'static' }
| { path: '/experimental/erc7821/client'; render: 'static' }
| { path: '/experimental/erc7821/execute'; render: 'static' }
| { path: '/experimental/erc7821/executeBatches'; render: 'static' }
| { path: '/experimental/erc7821/supportsExecutionMode'; render: 'static' }
| { path: '/experimental/erc7811/client'; render: 'static' }
| { path: '/experimental/erc7811/getAssets'; render: 'static' }
| { path: '/experimental/erc7739/client'; render: 'static' }
| { path: '/experimental/erc7739/hashMessage'; render: 'static' }
| { path: '/experimental/erc7739/hashTypedData'; render: 'static' }
| { path: '/experimental/erc7739/signMessage'; render: 'static' }
| { path: '/experimental/erc7739/signTypedData'; render: 'static' }
| { path: '/experimental/erc7739/wrapTypedDataSignature'; render: 'static' }
| { path: '/experimental/erc7715/client'; render: 'static' }
| { path: '/experimental/erc7715/grantPermissions'; render: 'static' }
| { path: '/docs/compatibility'; render: 'static' }
| { path: '/docs/eip7702'; render: 'static' }
| { path: '/docs/error-handling'; render: 'static' }
| { path: '/docs/ethers-migration'; render: 'static' }
| { path: '/docs/faq'; render: 'static' }
| { path: '/docs/getting-started'; render: 'static' }
| { path: '/docs/installation'; render: 'static' }
| { path: '/docs/introduction'; render: 'static' }
| { path: '/docs/migration-guide'; render: 'static' }
| { path: '/docs/typescript'; render: 'static' }
| { path: '/docs/utilities/blobsToCommitments'; render: 'static' }
| { path: '/docs/utilities/blobsToProofs'; render: 'static' }
| { path: '/docs/utilities/commitmentToVersionedHash'; render: 'static' }
| { path: '/docs/utilities/commitmentsToVersionedHashes'; render: 'static' }
| { path: '/docs/utilities/compactSignatureToSignature'; render: 'static' }
| { path: '/docs/utilities/concat'; render: 'static' }
| { path: '/docs/utilities/defineKzg'; render: 'static' }
| { path: '/docs/utilities/extractChain'; render: 'static' }
| { path: '/docs/utilities/formatEther'; render: 'static' }
| { path: '/docs/utilities/formatGwei'; render: 'static' }
| { path: '/docs/utilities/formatUnits'; render: 'static' }
| { path: '/docs/utilities/fromBase58'; render: 'static' }
| { path: '/docs/utilities/fromBase64'; render: 'static' }
| { path: '/docs/utilities/fromBlobs'; render: 'static' }
| { path: '/docs/utilities/fromBytes'; render: 'static' }
| { path: '/docs/utilities/fromHex'; render: 'static' }
| { path: '/docs/utilities/fromRlp'; render: 'static' }
| { path: '/docs/utilities/getAddress'; render: 'static' }
| { path: '/docs/utilities/getContractAddress'; render: 'static' }
| { path: '/docs/utilities/hashMessage'; render: 'static' }
| { path: '/docs/utilities/hashTypedData'; render: 'static' }
| { path: '/docs/utilities/isAddress'; render: 'static' }
| { path: '/docs/utilities/isAddressEqual'; render: 'static' }
| { path: '/docs/utilities/isBytes'; render: 'static' }
| { path: '/docs/utilities/isErc6492Signature'; render: 'static' }
| { path: '/docs/utilities/isHash'; render: 'static' }
| { path: '/docs/utilities/isHex'; render: 'static' }
| { path: '/docs/utilities/keccak256'; render: 'static' }
| { path: '/docs/utilities/pad'; render: 'static' }
| { path: '/docs/utilities/parseCompactSignature'; render: 'static' }
| { path: '/docs/utilities/parseErc6492Signature'; render: 'static' }
| { path: '/docs/utilities/parseEther'; render: 'static' }
| { path: '/docs/utilities/parseGwei'; render: 'static' }
| { path: '/docs/utilities/parseSignature'; render: 'static' }
| { path: '/docs/utilities/parseTransaction'; render: 'static' }
| { path: '/docs/utilities/parseUnits'; render: 'static' }
| { path: '/docs/utilities/recoverAddress'; render: 'static' }
| { path: '/docs/utilities/recoverMessageAddress'; render: 'static' }
| { path: '/docs/utilities/recoverPublicKey'; render: 'static' }
| { path: '/docs/utilities/recoverTransactionAddress'; render: 'static' }
| { path: '/docs/utilities/recoverTypedDataAddress'; render: 'static' }
| { path: '/docs/utilities/ripemd160'; render: 'static' }
| { path: '/docs/utilities/serializeCompactSignature'; render: 'static' }
| { path: '/docs/utilities/serializeErc6492Signature'; render: 'static' }
| { path: '/docs/utilities/serializeSignature'; render: 'static' }
| { path: '/docs/utilities/serializeTransaction'; render: 'static' }
| { path: '/docs/utilities/setupKzg'; render: 'static' }
| { path: '/docs/utilities/sha256'; render: 'static' }
| { path: '/docs/utilities/sidecarsToVersionedHashes'; render: 'static' }
| { path: '/docs/utilities/signatureToCompactSignature'; render: 'static' }
| { path: '/docs/utilities/size'; render: 'static' }
| { path: '/docs/utilities/slice'; render: 'static' }
| { path: '/docs/utilities/toBase58'; render: 'static' }
| { path: '/docs/utilities/toBase64'; render: 'static' }
| { path: '/docs/utilities/toBlobSidecars'; render: 'static' }
| { path: '/docs/utilities/toBlobs'; render: 'static' }
| { path: '/docs/utilities/toBytes'; render: 'static' }
| { path: '/docs/utilities/toEventHash'; render: 'static' }
| { path: '/docs/utilities/toEventSelector'; render: 'static' }
| { path: '/docs/utilities/toEventSignature'; render: 'static' }
| { path: '/docs/utilities/toFunctionHash'; render: 'static' }
| { path: '/docs/utilities/toFunctionSelector'; render: 'static' }
| { path: '/docs/utilities/toFunctionSignature'; render: 'static' }
| { path: '/docs/utilities/toHex'; render: 'static' }
| { path: '/docs/utilities/toRlp'; render: 'static' }
| { path: '/docs/utilities/trim'; render: 'static' }
| { path: '/docs/utilities/verifyMessage'; render: 'static' }
| { path: '/docs/utilities/verifyTypedData'; render: 'static' }
| { path: '/docs/siwe/utilities/createSiweMessage'; render: 'static' }
| { path: '/docs/siwe/utilities/generateSiweNonce'; render: 'static' }
| { path: '/docs/siwe/utilities/parseSiweMessage'; render: 'static' }
| { path: '/docs/siwe/utilities/validateSiweMessage'; render: 'static' }
| { path: '/docs/siwe/actions/verifySiweMessage'; render: 'static' }
| { path: '/docs/guides/blob-transactions'; render: 'static' }
| { path: '/docs/glossary/errors'; render: 'static' }
| { path: '/docs/glossary/terms'; render: 'static' }
| { path: '/docs/glossary/types'; render: 'static' }
| { path: '/docs/ens/utilities/labelhash'; render: 'static' }
| { path: '/docs/ens/utilities/namehash'; render: 'static' }
| { path: '/docs/ens/utilities/normalize'; render: 'static' }
| { path: '/docs/ens/actions/getEnsAddress'; render: 'static' }
| { path: '/docs/ens/actions/getEnsAvatar'; render: 'static' }
| { path: '/docs/ens/actions/getEnsName'; render: 'static' }
| { path: '/docs/ens/actions/getEnsResolver'; render: 'static' }
| { path: '/docs/ens/actions/getEnsText'; render: 'static' }
| { path: '/docs/eip7702/contract-writes'; render: 'static' }
| { path: '/docs/eip7702/hashAuthorization'; render: 'static' }
| { path: '/docs/eip7702/prepareAuthorization'; render: 'static' }
| { path: '/docs/eip7702/recoverAuthorizationAddress'; render: 'static' }
| { path: '/docs/eip7702/sending-transactions'; render: 'static' }
| { path: '/docs/eip7702/signAuthorization'; render: 'static' }
| { path: '/docs/eip7702/verifyAuthorization'; render: 'static' }
| { path: '/docs/contract/createContractEventFilter'; render: 'static' }
| { path: '/docs/contract/decodeDeployData'; render: 'static' }
| { path: '/docs/contract/decodeErrorResult'; render: 'static' }
| { path: '/docs/contract/decodeEventLog'; render: 'static' }
| { path: '/docs/contract/decodeFunctionData'; render: 'static' }
| { path: '/docs/contract/decodeFunctionResult'; render: 'static' }
| { path: '/docs/contract/deployContract'; render: 'static' }
| { path: '/docs/contract/encodeDeployData'; render: 'static' }
| { path: '/docs/contract/encodeErrorResult'; render: 'static' }
| { path: '/docs/contract/encodeEventTopics'; render: 'static' }
| { path: '/docs/contract/encodeFunctionData'; render: 'static' }
| { path: '/docs/contract/encodeFunctionResult'; render: 'static' }
| { path: '/docs/contract/estimateContractGas'; render: 'static' }
| { path: '/docs/contract/getCode'; render: 'static' }
| { path: '/docs/contract/getContract'; render: 'static' }
| { path: '/docs/contract/getContractEvents'; render: 'static' }
| { path: '/docs/contract/getStorageAt'; render: 'static' }
| { path: '/docs/contract/multicall'; render: 'static' }
| { path: '/docs/contract/parseEventLogs'; render: 'static' }
| { path: '/docs/contract/readContract'; render: 'static' }
| { path: '/docs/contract/simulateContract'; render: 'static' }
| { path: '/docs/contract/watchContractEvent'; render: 'static' }
| { path: '/docs/contract/writeContract'; render: 'static' }
| { path: '/docs/contract/writeContractSync'; render: 'static' }
| { path: '/docs/clients/custom'; render: 'static' }
| { path: '/docs/clients/intro'; render: 'static' }
| { path: '/docs/clients/public'; render: 'static' }
| { path: '/docs/clients/test'; render: 'static' }
| { path: '/docs/clients/wallet'; render: 'static' }
| { path: '/docs/clients/transports/custom'; render: 'static' }
| { path: '/docs/clients/transports/fallback'; render: 'static' }
| { path: '/docs/clients/transports/http'; render: 'static' }
| { path: '/docs/clients/transports/ipc'; render: 'static' }
| { path: '/docs/clients/transports/websocket'; render: 'static' }
| { path: '/docs/chains/celo'; render: 'static' }
| { path: '/docs/chains/fees'; render: 'static' }
| { path: '/docs/chains/formatters'; render: 'static' }
| { path: '/docs/chains/introduction'; render: 'static' }
| { path: '/docs/chains/serializers'; render: 'static' }
| { path: '/docs/chains/zksync'; render: 'static' }
| { path: '/docs/actions/wallet/addChain'; render: 'static' }
| { path: '/docs/actions/wallet/getAddresses'; render: 'static' }
| { path: '/docs/actions/wallet/getCallsStatus'; render: 'static' }
| { path: '/docs/actions/wallet/getCapabilities'; render: 'static' }
| { path: '/docs/actions/wallet/getPermissions'; render: 'static' }
| { path: '/docs/actions/wallet/introduction'; render: 'static' }
| { path: '/docs/actions/wallet/prepareTransactionRequest'; render: 'static' }
| { path: '/docs/actions/wallet/requestAddresses'; render: 'static' }
| { path: '/docs/actions/wallet/requestPermissions'; render: 'static' }
| { path: '/docs/actions/wallet/sendCalls'; render: 'static' }
| { path: '/docs/actions/wallet/sendCallsSync'; render: 'static' }
| { path: '/docs/actions/wallet/sendRawTransaction'; render: 'static' }
| { path: '/docs/actions/wallet/sendRawTransactionSync'; render: 'static' }
| { path: '/docs/actions/wallet/sendTransaction'; render: 'static' }
| { path: '/docs/actions/wallet/sendTransactionSync'; render: 'static' }
| { path: '/docs/actions/wallet/showCallsStatus'; render: 'static' }
| { path: '/docs/actions/wallet/signMessage'; render: 'static' }
| { path: '/docs/actions/wallet/signTransaction'; render: 'static' }
| { path: '/docs/actions/wallet/signTypedData'; render: 'static' }
| { path: '/docs/actions/wallet/switchChain'; render: 'static' }
| { path: '/docs/actions/wallet/waitForCallsStatus'; render: 'static' }
| { path: '/docs/actions/wallet/watchAsset'; render: 'static' }
| { path: '/docs/actions/test/dropTransaction'; render: 'static' }
| { path: '/docs/actions/test/dumpState'; render: 'static' }
| { path: '/docs/actions/test/getAutomine'; render: 'static' }
| { path: '/docs/actions/test/getTxpoolContent'; render: 'static' }
| { path: '/docs/actions/test/getTxpoolStatus'; render: 'static' }
| { path: '/docs/actions/test/impersonateAccount'; render: 'static' }
| { path: '/docs/actions/test/increaseTime'; render: 'static' }
| { path: '/docs/actions/test/inspectTxpool'; render: 'static' }
| { path: '/docs/actions/test/introduction'; render: 'static' }
| { path: '/docs/actions/test/loadState'; render: 'static' }
| { path: '/docs/actions/test/mine'; render: 'static' }
| { path: '/docs/actions/test/removeBlockTimestampInterval'; render: 'static' }
| { path: '/docs/actions/test/reset'; render: 'static' }
| { path: '/docs/actions/test/revert'; render: 'static' }
| { path: '/docs/actions/test/sendUnsignedTransaction'; render: 'static' }
| { path: '/docs/actions/test/setAutomine'; render: 'static' }
| { path: '/docs/actions/test/setBalance'; render: 'static' }
| { path: '/docs/actions/test/setBlockGasLimit'; render: 'static' }
| { path: '/docs/actions/test/setBlockTimestampInterval'; render: 'static' }
| { path: '/docs/actions/test/setCode'; render: 'static' }
| { path: '/docs/actions/test/setCoinbase'; render: 'static' }
| { path: '/docs/actions/test/setIntervalMining'; render: 'static' }
| { path: '/docs/actions/test/setLoggingEnabled'; render: 'static' }
| { path: '/docs/actions/test/setMinGasPrice'; render: 'static' }
| { path: '/docs/actions/test/setNextBlockBaseFeePerGas'; render: 'static' }
| { path: '/docs/actions/test/setNextBlockTimestamp'; render: 'static' }
| { path: '/docs/actions/test/setNonce'; render: 'static' }
| { path: '/docs/actions/test/setRpcUrl'; render: 'static' }
| { path: '/docs/actions/test/setStorageAt'; render: 'static' }
| { path: '/docs/actions/test/snapshot'; render: 'static' }
| { path: '/docs/actions/test/stopImpersonatingAccount'; render: 'static' }
| { path: '/docs/actions/public/call'; render: 'static' }
| { path: '/docs/actions/public/createAccessList'; render: 'static' }
| { path: '/docs/actions/public/createBlockFilter'; render: 'static' }
| { path: '/docs/actions/public/createEventFilter'; render: 'static' }
| { path: '/docs/actions/public/createPendingTransactionFilter'; render: 'static' }
| { path: '/docs/actions/public/estimateFeesPerGas'; render: 'static' }
| { path: '/docs/actions/public/estimateGas'; render: 'static' }
| { path: '/docs/actions/public/estimateMaxPriorityFeePerGas'; render: 'static' }
| { path: '/docs/actions/public/getBalance'; render: 'static' }
| { path: '/docs/actions/public/getBlobBaseFee'; render: 'static' }
| { path: '/docs/actions/public/getBlock'; render: 'static' }
| { path: '/docs/actions/public/getBlockNumber'; render: 'static' }
| { path: '/docs/actions/public/getBlockTransactionCount'; render: 'static' }
| { path: '/docs/actions/public/getChainId'; render: 'static' }
| { path: '/docs/actions/public/getEip712Domain'; render: 'static' }
| { path: '/docs/actions/public/getFeeHistory'; render: 'static' }
| { path: '/docs/actions/public/getFilterChanges'; render: 'static' }
| { path: '/docs/actions/public/getFilterLogs'; render: 'static' }
| { path: '/docs/actions/public/getGasPrice'; render: 'static' }
| { path: '/docs/actions/public/getLogs'; render: 'static' }
| { path: '/docs/actions/public/getProof'; render: 'static' }
| { path: '/docs/actions/public/getTransaction'; render: 'static' }
| { path: '/docs/actions/public/getTransactionConfirmations'; render: 'static' }
| { path: '/docs/actions/public/getTransactionCount'; render: 'static' }
| { path: '/docs/actions/public/getTransactionReceipt'; render: 'static' }
| { path: '/docs/actions/public/introduction'; render: 'static' }
| { path: '/docs/actions/public/simulateBlocks'; render: 'static' }
| { path: '/docs/actions/public/simulateCalls'; render: 'static' }
| { path: '/docs/actions/public/uninstallFilter'; render: 'static' }
| { path: '/docs/actions/public/verifyHash'; render: 'static' }
| { path: '/docs/actions/public/verifyMessage'; render: 'static' }
| { path: '/docs/actions/public/verifyTypedData'; render: 'static' }
| { path: '/docs/actions/public/waitForTransactionReceipt'; render: 'static' }
| { path: '/docs/actions/public/watchBlockNumber'; render: 'static' }
| { path: '/docs/actions/public/watchBlocks'; render: 'static' }
| { path: '/docs/actions/public/watchEvent'; render: 'static' }
| { path: '/docs/actions/public/watchPendingTransactions'; render: 'static' }
| { path: '/docs/accounts/jsonRpc'; render: 'static' }
| { path: '/docs/accounts/local'; render: 'static' }
| { path: '/docs/accounts/local/createNonceManager'; render: 'static' }
| { path: '/docs/accounts/local/hdKeyToAccount'; render: 'static' }
| { path: '/docs/accounts/local/mnemonicToAccount'; render: 'static' }
| { path: '/docs/accounts/local/privateKeyToAccount'; render: 'static' }
| { path: '/docs/accounts/local/signMessage'; render: 'static' }
| { path: '/docs/accounts/local/signTransaction'; render: 'static' }
| { path: '/docs/accounts/local/signTypedData'; render: 'static' }
| { path: '/docs/accounts/local/toAccount'; render: 'static' }
| { path: '/docs/abi/decodeAbiParameters'; render: 'static' }
| { path: '/docs/abi/encodeAbiParameters'; render: 'static' }
| { path: '/docs/abi/encodePacked'; render: 'static' }
| { path: '/docs/abi/getAbiItem'; render: 'static' }
| { path: '/docs/abi/parseAbi'; render: 'static' }
| { path: '/docs/abi/parseAbiItem'; render: 'static' }
| { path: '/docs/abi/parseAbiParameter'; render: 'static' }
| { path: '/docs/abi/parseAbiParameters'; render: 'static' }
| { path: '/components/Sponsors'; render: 'static' }
| { path: '/circle-usdc/guides/bridge-kit'; render: 'static' }
| { path: '/circle-usdc/guides/cross-chain'; render: 'static' }
| { path: '/circle-usdc/guides/integrating'; render: 'static' }
| { path: '/circle-usdc/guides/manual-cctp'; render: 'static' }
| { path: '/circle-usdc/guides/paymaster'; render: 'static' }
| { path: '/circle-usdc/guides/smart-account'; render: 'static' }
| { path: '/account-abstraction/guides/sending-user-operations'; render: 'static' }
| { path: '/account-abstraction/clients/bundler'; render: 'static' }
| { path: '/account-abstraction/clients/paymaster'; render: 'static' }
| { path: '/account-abstraction/actions/paymaster/getPaymasterData'; render: 'static' }
| { path: '/account-abstraction/actions/paymaster/getPaymasterStubData'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/estimateUserOperationGas'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/getChainId'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/getSupportedEntryPoints'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/getUserOperation'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/getUserOperationReceipt'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/introduction'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/prepareUserOperation'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/sendUserOperation'; render: 'static' }
| { path: '/account-abstraction/actions/bundler/waitForUserOperationReceipt'; render: 'static' }
| { path: '/account-abstraction/accounts/smart'; render: 'static' }
| { path: '/account-abstraction/accounts/webauthn'; render: 'static' }
| { path: '/account-abstraction/accounts/webauthn/createWebAuthnCredential'; render: 'static' }
| { path: '/account-abstraction/accounts/webauthn/toWebAuthnAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/signMessage'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/signTypedData'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/signUserOperation'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toCoinbaseSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toEcdsaKernelSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toLightSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toMetaMaskSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toNexusSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toSafeSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toSimpleSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toSoladySmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toThirdwebSmartAccount'; render: 'static' }
| { path: '/account-abstraction/accounts/smart/toTrustSmartAccount'; render: 'static' };

// prettier-ignore
declare module 'waku/router' {
  interface RouteConfig {
    paths: PathsForPages<Page>;
  }
  interface CreatePagesConfig {
    pages: Page;
  }
}
