// AUTOGENERATED by `pnpm docs:sync-utils` — do not edit by hand.
import type { Config } from 'vocs/config'

type SidebarItem = Extract<
  NonNullable<Config['sidebar']>,
  readonly unknown[]
>[number]

export const utilities = {
  text: 'Utilities',
  collapsed: false,
  items: [
    {
      text: 'ABI',
      collapsed: true,
      items: [
        {
          text: 'Abi',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abi',
            },
            {
              text: 'from',
              link: '/docs/utilities/abi/from',
            },
            {
              text: 'format',
              link: '/docs/utilities/abi/format',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abi/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abi/types',
            },
          ],
        },
        {
          text: 'AbiConstructor',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abiconstructor',
            },
            {
              text: 'fromAbi',
              link: '/docs/utilities/abiconstructor/fromAbi',
            },
            {
              text: 'from',
              link: '/docs/utilities/abiconstructor/from',
            },
            {
              text: 'encode',
              link: '/docs/utilities/abiconstructor/encode',
            },
            {
              text: 'decode',
              link: '/docs/utilities/abiconstructor/decode',
            },
            {
              text: 'format',
              link: '/docs/utilities/abiconstructor/format',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abiconstructor/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abiconstructor/types',
            },
          ],
        },
        {
          text: 'AbiError',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abierror',
            },
            {
              text: 'fromAbi',
              link: '/docs/utilities/abierror/fromAbi',
            },
            {
              text: 'from',
              link: '/docs/utilities/abierror/from',
            },
            {
              text: 'decode',
              link: '/docs/utilities/abierror/decode',
            },
            {
              text: 'encode',
              link: '/docs/utilities/abierror/encode',
            },
            {
              text: 'extract',
              link: '/docs/utilities/abierror/extract',
            },
            {
              text: 'format',
              link: '/docs/utilities/abierror/format',
            },
            {
              text: 'getSelector',
              link: '/docs/utilities/abierror/getSelector',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abierror/types',
            },
          ],
        },
        {
          text: 'AbiEvent',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abievent',
            },
            {
              text: 'fromAbi',
              link: '/docs/utilities/abievent/fromAbi',
            },
            {
              text: 'from',
              link: '/docs/utilities/abievent/from',
            },
            {
              text: 'encode',
              link: '/docs/utilities/abievent/encode',
            },
            {
              text: 'decode',
              link: '/docs/utilities/abievent/decode',
            },
            {
              text: 'assertArgs',
              link: '/docs/utilities/abievent/assertArgs',
            },
            {
              text: 'decodeLog',
              link: '/docs/utilities/abievent/decodeLog',
            },
            {
              text: 'extractLogs',
              link: '/docs/utilities/abievent/extractLogs',
            },
            {
              text: 'format',
              link: '/docs/utilities/abievent/format',
            },
            {
              text: 'getSelector',
              link: '/docs/utilities/abievent/getSelector',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abievent/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abievent/types',
            },
          ],
        },
        {
          text: 'AbiFunction',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abifunction',
            },
            {
              text: 'fromAbi',
              link: '/docs/utilities/abifunction/fromAbi',
            },
            {
              text: 'from',
              link: '/docs/utilities/abifunction/from',
            },
            {
              text: 'encodeData',
              link: '/docs/utilities/abifunction/encodeData',
            },
            {
              text: 'decodeResult',
              link: '/docs/utilities/abifunction/decodeResult',
            },
            {
              text: 'decodeData',
              link: '/docs/utilities/abifunction/decodeData',
            },
            {
              text: 'encodeResult',
              link: '/docs/utilities/abifunction/encodeResult',
            },
            {
              text: 'format',
              link: '/docs/utilities/abifunction/format',
            },
            {
              text: 'getSelector',
              link: '/docs/utilities/abifunction/getSelector',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abifunction/types',
            },
          ],
        },
        {
          text: 'AbiItem',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abiitem',
            },
            {
              text: 'fromAbi',
              link: '/docs/utilities/abiitem/fromAbi',
            },
            {
              text: 'format',
              link: '/docs/utilities/abiitem/format',
            },
            {
              text: 'from',
              link: '/docs/utilities/abiitem/from',
            },
            {
              text: 'getSelector',
              link: '/docs/utilities/abiitem/getSelector',
            },
            {
              text: 'getSignature',
              link: '/docs/utilities/abiitem/getSignature',
            },
            {
              text: 'getSignatureHash',
              link: '/docs/utilities/abiitem/getSignatureHash',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abiitem/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abiitem/types',
            },
          ],
        },
        {
          text: 'AbiParameter',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abiparameter',
            },
            {
              text: 'from',
              link: '/docs/utilities/abiparameter/from',
            },
            {
              text: 'format',
              link: '/docs/utilities/abiparameter/format',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abiparameter/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abiparameter/types',
            },
          ],
        },
        {
          text: 'AbiParameters',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/abiparameters',
            },
            {
              text: 'encode',
              link: '/docs/utilities/abiparameters/encode',
            },
            {
              text: 'from',
              link: '/docs/utilities/abiparameters/from',
            },
            {
              text: 'decode',
              link: '/docs/utilities/abiparameters/decode',
            },
            {
              text: 'encodePacked',
              link: '/docs/utilities/abiparameters/encodePacked',
            },
            {
              text: 'format',
              link: '/docs/utilities/abiparameters/format',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/abiparameters/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/abiparameters/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Access List',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/accesslist',
        },
        {
          text: 'fromTupleList',
          link: '/docs/utilities/accesslist/fromTupleList',
        },
        {
          text: 'toTupleList',
          link: '/docs/utilities/accesslist/toTupleList',
        },
        {
          text: 'Errors',
          link: '/docs/utilities/accesslist/errors',
        },
        {
          text: 'Types',
          link: '/docs/utilities/accesslist/types',
        },
      ],
    },
    {
      text: 'Account Proof',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/accountproof',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/accountproof/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/accountproof/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/accountproof/types',
        },
      ],
    },
    {
      text: 'Addresses',
      collapsed: true,
      items: [
        {
          text: 'Address',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/address',
            },
            {
              text: 'from',
              link: '/docs/utilities/address/from',
            },
            {
              text: 'validate',
              link: '/docs/utilities/address/validate',
            },
            {
              text: 'assert',
              link: '/docs/utilities/address/assert',
            },
            {
              text: 'fromPublicKey',
              link: '/docs/utilities/address/fromPublicKey',
            },
            {
              text: 'checksum',
              link: '/docs/utilities/address/checksum',
            },
            {
              text: 'isEqual',
              link: '/docs/utilities/address/isEqual',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/address/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/address/types',
            },
          ],
        },
        {
          text: 'ContractAddress',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/contractaddress',
            },
            {
              text: 'fromCreate',
              link: '/docs/utilities/contractaddress/fromCreate',
            },
            {
              text: 'fromCreate2',
              link: '/docs/utilities/contractaddress/fromCreate2',
            },
            {
              text: 'from',
              link: '/docs/utilities/contractaddress/from',
            },
          ],
        },
      ],
    },
    {
      text: 'Authorization (EIP-7702)',
      collapsed: true,
      items: [
        {
          text: 'Authorization',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/authorization',
            },
            {
              text: 'from',
              link: '/docs/utilities/authorization/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/authorization/getSignPayload',
            },
            {
              text: 'fromRpc',
              link: '/docs/utilities/authorization/fromRpc',
            },
            {
              text: 'fromRpcList',
              link: '/docs/utilities/authorization/fromRpcList',
            },
            {
              text: 'fromTuple',
              link: '/docs/utilities/authorization/fromTuple',
            },
            {
              text: 'fromTupleList',
              link: '/docs/utilities/authorization/fromTupleList',
            },
            {
              text: 'hash',
              link: '/docs/utilities/authorization/hash',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/authorization/toRpc',
            },
            {
              text: 'toRpcList',
              link: '/docs/utilities/authorization/toRpcList',
            },
            {
              text: 'toTuple',
              link: '/docs/utilities/authorization/toTuple',
            },
            {
              text: 'toTupleList',
              link: '/docs/utilities/authorization/toTupleList',
            },
            {
              text: 'recoverAddress',
              link: '/docs/utilities/authorization/recoverAddress',
            },
            {
              text: 'verify',
              link: '/docs/utilities/authorization/verify',
            },
            {
              text: 'Types',
              link: '/docs/utilities/authorization/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Blobs (EIP-4844)',
      collapsed: true,
      items: [
        {
          text: 'BlobCells',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/blobcells',
            },
            {
              text: 'fromBlob',
              link: '/docs/utilities/blobcells/fromBlob',
            },
            {
              text: 'recover',
              link: '/docs/utilities/blobcells/recover',
            },
            {
              text: 'toDataColumns',
              link: '/docs/utilities/blobcells/toDataColumns',
            },
            {
              text: 'verify',
              link: '/docs/utilities/blobcells/verify',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/blobcells/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/blobcells/types',
            },
          ],
        },
        {
          text: 'Blobs',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/blobs',
            },
            {
              text: 'commitmentsToVersionedHashes',
              link: '/docs/utilities/blobs/commitmentsToVersionedHashes',
            },
            {
              text: 'commitmentToVersionedHash',
              link: '/docs/utilities/blobs/commitmentToVersionedHash',
            },
            {
              text: 'from',
              link: '/docs/utilities/blobs/from',
            },
            {
              text: 'to',
              link: '/docs/utilities/blobs/to',
            },
            {
              text: 'toBytes',
              link: '/docs/utilities/blobs/toBytes',
            },
            {
              text: 'toCellProofs',
              link: '/docs/utilities/blobs/toCellProofs',
            },
            {
              text: 'toCommitments',
              link: '/docs/utilities/blobs/toCommitments',
            },
            {
              text: 'toHex',
              link: '/docs/utilities/blobs/toHex',
            },
            {
              text: 'toVersionedHashes',
              link: '/docs/utilities/blobs/toVersionedHashes',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/blobs/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/blobs/types',
            },
          ],
        },
        {
          text: 'Kzg',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/kzg',
            },
            {
              text: 'from',
              link: '/docs/utilities/kzg/from',
            },
            {
              text: 'Types',
              link: '/docs/utilities/kzg/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Block',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/block',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/block/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/block/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/block/types',
        },
      ],
    },
    {
      text: 'Block Overrides',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/blockoverrides',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/blockoverrides/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/blockoverrides/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/blockoverrides/types',
        },
      ],
    },
    {
      text: 'Crypto',
      collapsed: true,
      items: [
        {
          text: 'Hash',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/hash',
            },
            {
              text: 'hmac256',
              link: '/docs/utilities/hash/hmac256',
            },
            {
              text: 'keccak256',
              link: '/docs/utilities/hash/keccak256',
            },
            {
              text: 'ripemd160',
              link: '/docs/utilities/hash/ripemd160',
            },
            {
              text: 'sha256',
              link: '/docs/utilities/hash/sha256',
            },
            {
              text: 'validate',
              link: '/docs/utilities/hash/validate',
            },
          ],
        },
        {
          text: 'HdKey',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/hdkey',
            },
            {
              text: 'fromExtendedKey',
              link: '/docs/utilities/hdkey/fromExtendedKey',
            },
            {
              text: 'fromJson',
              link: '/docs/utilities/hdkey/fromJson',
            },
            {
              text: 'fromSeed',
              link: '/docs/utilities/hdkey/fromSeed',
            },
            {
              text: 'path',
              link: '/docs/utilities/hdkey/path',
            },
            {
              text: 'Types',
              link: '/docs/utilities/hdkey/types',
            },
          ],
        },
        {
          text: 'Mnemonic',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/mnemonic',
            },
            {
              text: 'random',
              link: '/docs/utilities/mnemonic/random',
            },
            {
              text: 'toPrivateKey',
              link: '/docs/utilities/mnemonic/toPrivateKey',
            },
            {
              text: 'toHdKey',
              link: '/docs/utilities/mnemonic/toHdKey',
            },
            {
              text: 'toSeed',
              link: '/docs/utilities/mnemonic/toSeed',
            },
            {
              text: 'path',
              link: '/docs/utilities/mnemonic/path',
            },
            {
              text: 'validate',
              link: '/docs/utilities/mnemonic/validate',
            },
          ],
        },
        {
          text: 'P256',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/p256',
            },
            {
              text: 'randomPrivateKey',
              link: '/docs/utilities/p256/randomPrivateKey',
            },
            {
              text: 'getPublicKey',
              link: '/docs/utilities/p256/getPublicKey',
            },
            {
              text: 'sign',
              link: '/docs/utilities/p256/sign',
            },
            {
              text: 'verify',
              link: '/docs/utilities/p256/verify',
            },
            {
              text: 'createKeyPair',
              link: '/docs/utilities/p256/createKeyPair',
            },
            {
              text: 'getSharedSecret',
              link: '/docs/utilities/p256/getSharedSecret',
            },
            {
              text: 'recoverPublicKey',
              link: '/docs/utilities/p256/recoverPublicKey',
            },
          ],
        },
        {
          text: 'WebAuthnP256',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/webauthnp256',
            },
            {
              text: 'createCredential',
              link: '/docs/utilities/webauthnp256/createCredential',
            },
            {
              text: 'sign',
              link: '/docs/utilities/webauthnp256/sign',
            },
            {
              text: 'verify',
              link: '/docs/utilities/webauthnp256/verify',
            },
            {
              text: 'Types',
              link: '/docs/utilities/webauthnp256/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Encoding',
      collapsed: true,
      items: [
        {
          text: 'Bytes',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/bytes',
            },
            {
              text: 'fromArray',
              link: '/docs/utilities/bytes/fromArray',
            },
            {
              text: 'fromBoolean',
              link: '/docs/utilities/bytes/fromBoolean',
            },
            {
              text: 'fromHex',
              link: '/docs/utilities/bytes/fromHex',
            },
            {
              text: 'fromNumber',
              link: '/docs/utilities/bytes/fromNumber',
            },
            {
              text: 'fromString',
              link: '/docs/utilities/bytes/fromString',
            },
            {
              text: 'toBigInt',
              link: '/docs/utilities/bytes/toBigInt',
            },
            {
              text: 'toBoolean',
              link: '/docs/utilities/bytes/toBoolean',
            },
            {
              text: 'toHex',
              link: '/docs/utilities/bytes/toHex',
            },
            {
              text: 'toNumber',
              link: '/docs/utilities/bytes/toNumber',
            },
            {
              text: 'toString',
              link: '/docs/utilities/bytes/toString',
            },
            {
              text: 'concat',
              link: '/docs/utilities/bytes/concat',
            },
            {
              text: 'slice',
              link: '/docs/utilities/bytes/slice',
            },
            {
              text: 'padLeft',
              link: '/docs/utilities/bytes/padLeft',
            },
            {
              text: 'padRight',
              link: '/docs/utilities/bytes/padRight',
            },
            {
              text: 'trimLeft',
              link: '/docs/utilities/bytes/trimLeft',
            },
            {
              text: 'trimRight',
              link: '/docs/utilities/bytes/trimRight',
            },
            {
              text: 'assert',
              link: '/docs/utilities/bytes/assert',
            },
            {
              text: 'from',
              link: '/docs/utilities/bytes/from',
            },
            {
              text: 'isEqual',
              link: '/docs/utilities/bytes/isEqual',
            },
            {
              text: 'random',
              link: '/docs/utilities/bytes/random',
            },
            {
              text: 'size',
              link: '/docs/utilities/bytes/size',
            },
            {
              text: 'validate',
              link: '/docs/utilities/bytes/validate',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/bytes/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/bytes/types',
            },
          ],
        },
        {
          text: 'Hex',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/hex',
            },
            {
              text: 'fromBoolean',
              link: '/docs/utilities/hex/fromBoolean',
            },
            {
              text: 'fromBytes',
              link: '/docs/utilities/hex/fromBytes',
            },
            {
              text: 'fromNumber',
              link: '/docs/utilities/hex/fromNumber',
            },
            {
              text: 'fromString',
              link: '/docs/utilities/hex/fromString',
            },
            {
              text: 'toBoolean',
              link: '/docs/utilities/hex/toBoolean',
            },
            {
              text: 'toBytes',
              link: '/docs/utilities/hex/toBytes',
            },
            {
              text: 'toNumber',
              link: '/docs/utilities/hex/toNumber',
            },
            {
              text: 'toString',
              link: '/docs/utilities/hex/toString',
            },
            {
              text: 'concat',
              link: '/docs/utilities/hex/concat',
            },
            {
              text: 'slice',
              link: '/docs/utilities/hex/slice',
            },
            {
              text: 'padLeft',
              link: '/docs/utilities/hex/padLeft',
            },
            {
              text: 'padRight',
              link: '/docs/utilities/hex/padRight',
            },
            {
              text: 'trimLeft',
              link: '/docs/utilities/hex/trimLeft',
            },
            {
              text: 'trimRight',
              link: '/docs/utilities/hex/trimRight',
            },
            {
              text: 'assert',
              link: '/docs/utilities/hex/assert',
            },
            {
              text: 'from',
              link: '/docs/utilities/hex/from',
            },
            {
              text: 'isEqual',
              link: '/docs/utilities/hex/isEqual',
            },
            {
              text: 'random',
              link: '/docs/utilities/hex/random',
            },
            {
              text: 'size',
              link: '/docs/utilities/hex/size',
            },
            {
              text: 'toBigInt',
              link: '/docs/utilities/hex/toBigInt',
            },
            {
              text: 'validate',
              link: '/docs/utilities/hex/validate',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/hex/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/hex/types',
            },
          ],
        },
        {
          text: 'Json',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/json',
            },
            {
              text: 'stringify',
              link: '/docs/utilities/json/stringify',
            },
            {
              text: 'parse',
              link: '/docs/utilities/json/parse',
            },
            {
              text: 'canonicalize',
              link: '/docs/utilities/json/canonicalize',
            },
            {
              text: 'prettyPrint',
              link: '/docs/utilities/json/prettyPrint',
            },
          ],
        },
        {
          text: 'Rlp',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/rlp',
            },
            {
              text: 'from',
              link: '/docs/utilities/rlp/from',
            },
            {
              text: 'fromBytes',
              link: '/docs/utilities/rlp/fromBytes',
            },
            {
              text: 'fromHex',
              link: '/docs/utilities/rlp/fromHex',
            },
            {
              text: 'toBytes',
              link: '/docs/utilities/rlp/toBytes',
            },
            {
              text: 'toHex',
              link: '/docs/utilities/rlp/toHex',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/rlp/errors',
            },
          ],
        },
        {
          text: 'Value',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/value',
            },
            {
              text: 'format',
              link: '/docs/utilities/value/format',
            },
            {
              text: 'formatEther',
              link: '/docs/utilities/value/formatEther',
            },
            {
              text: 'formatGwei',
              link: '/docs/utilities/value/formatGwei',
            },
            {
              text: 'from',
              link: '/docs/utilities/value/from',
            },
            {
              text: 'fromEther',
              link: '/docs/utilities/value/fromEther',
            },
            {
              text: 'fromGwei',
              link: '/docs/utilities/value/fromGwei',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/value/errors',
            },
          ],
        },
      ],
    },
    {
      text: 'ENS',
      collapsed: true,
      items: [
        {
          text: 'Ens',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/ens',
            },
            {
              text: 'normalize',
              link: '/docs/utilities/ens/normalize',
            },
            {
              text: 'namehash',
              link: '/docs/utilities/ens/namehash',
            },
            {
              text: 'labelhash',
              link: '/docs/utilities/ens/labelhash',
            },
            {
              text: 'toCoinType',
              link: '/docs/utilities/ens/toCoinType',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/ens/errors',
            },
          ],
        },
      ],
    },
    {
      text: 'Fee',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/fee',
        },
        {
          text: 'effectiveGasPrice',
          link: '/docs/utilities/fee/effectiveGasPrice',
        },
        {
          text: 'estimateMaxFeePerGas',
          link: '/docs/utilities/fee/estimateMaxFeePerGas',
        },
        {
          text: 'fromHistoryRpc',
          link: '/docs/utilities/fee/fromHistoryRpc',
        },
        {
          text: 'toHistoryRpc',
          link: '/docs/utilities/fee/toHistoryRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/fee/types',
        },
      ],
    },
    {
      text: 'Filter',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/filter',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/filter/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/filter/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/filter/types',
        },
      ],
    },
    {
      text: 'JSON-RPC',
      collapsed: true,
      items: [
        {
          text: 'RpcResponse',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/rpcresponse',
            },
            {
              text: 'from',
              link: '/docs/utilities/rpcresponse/from',
            },
            {
              text: 'parse',
              link: '/docs/utilities/rpcresponse/parse',
            },
            {
              text: 'parseError',
              link: '/docs/utilities/rpcresponse/parseError',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/rpcresponse/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/rpcresponse/types',
            },
          ],
        },
        {
          text: 'RpcSchema',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/rpcschema',
            },
            {
              text: 'from',
              link: '/docs/utilities/rpcschema/from',
            },
            {
              text: 'Types',
              link: '/docs/utilities/rpcschema/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Keys & Signatures',
      collapsed: true,
      items: [
        {
          text: 'PublicKey',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/publickey',
            },
            {
              text: 'toHex',
              link: '/docs/utilities/publickey/toHex',
            },
            {
              text: 'fromHex',
              link: '/docs/utilities/publickey/fromHex',
            },
            {
              text: 'assert',
              link: '/docs/utilities/publickey/assert',
            },
            {
              text: 'compress',
              link: '/docs/utilities/publickey/compress',
            },
            {
              text: 'from',
              link: '/docs/utilities/publickey/from',
            },
            {
              text: 'fromBytes',
              link: '/docs/utilities/publickey/fromBytes',
            },
            {
              text: 'toBytes',
              link: '/docs/utilities/publickey/toBytes',
            },
            {
              text: 'validate',
              link: '/docs/utilities/publickey/validate',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/publickey/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/publickey/types',
            },
          ],
        },
        {
          text: 'Secp256k1',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/secp256k1',
            },
            {
              text: 'randomPrivateKey',
              link: '/docs/utilities/secp256k1/randomPrivateKey',
            },
            {
              text: 'getPublicKey',
              link: '/docs/utilities/secp256k1/getPublicKey',
            },
            {
              text: 'sign',
              link: '/docs/utilities/secp256k1/sign',
            },
            {
              text: 'verify',
              link: '/docs/utilities/secp256k1/verify',
            },
            {
              text: 'createKeyPair',
              link: '/docs/utilities/secp256k1/createKeyPair',
            },
            {
              text: 'getSharedSecret',
              link: '/docs/utilities/secp256k1/getSharedSecret',
            },
            {
              text: 'recoverAddress',
              link: '/docs/utilities/secp256k1/recoverAddress',
            },
            {
              text: 'recoverPublicKey',
              link: '/docs/utilities/secp256k1/recoverPublicKey',
            },
          ],
        },
        {
          text: 'Signature',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/signature',
            },
            {
              text: 'toHex',
              link: '/docs/utilities/signature/toHex',
            },
            {
              text: 'fromHex',
              link: '/docs/utilities/signature/fromHex',
            },
            {
              text: 'assert',
              link: '/docs/utilities/signature/assert',
            },
            {
              text: 'extract',
              link: '/docs/utilities/signature/extract',
            },
            {
              text: 'from',
              link: '/docs/utilities/signature/from',
            },
            {
              text: 'fromBytes',
              link: '/docs/utilities/signature/fromBytes',
            },
            {
              text: 'fromCompactBytes',
              link: '/docs/utilities/signature/fromCompactBytes',
            },
            {
              text: 'fromDerBytes',
              link: '/docs/utilities/signature/fromDerBytes',
            },
            {
              text: 'fromDerHex',
              link: '/docs/utilities/signature/fromDerHex',
            },
            {
              text: 'fromLegacy',
              link: '/docs/utilities/signature/fromLegacy',
            },
            {
              text: 'fromRecoveredBytes',
              link: '/docs/utilities/signature/fromRecoveredBytes',
            },
            {
              text: 'fromRpc',
              link: '/docs/utilities/signature/fromRpc',
            },
            {
              text: 'fromTuple',
              link: '/docs/utilities/signature/fromTuple',
            },
            {
              text: 'toBytes',
              link: '/docs/utilities/signature/toBytes',
            },
            {
              text: 'toCompactBytes',
              link: '/docs/utilities/signature/toCompactBytes',
            },
            {
              text: 'toDerBytes',
              link: '/docs/utilities/signature/toDerBytes',
            },
            {
              text: 'toDerHex',
              link: '/docs/utilities/signature/toDerHex',
            },
            {
              text: 'toLegacy',
              link: '/docs/utilities/signature/toLegacy',
            },
            {
              text: 'toRecoveredBytes',
              link: '/docs/utilities/signature/toRecoveredBytes',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/signature/toRpc',
            },
            {
              text: 'toTuple',
              link: '/docs/utilities/signature/toTuple',
            },
            {
              text: 'validate',
              link: '/docs/utilities/signature/validate',
            },
            {
              text: 'vToYParity',
              link: '/docs/utilities/signature/vToYParity',
            },
            {
              text: 'yParityToV',
              link: '/docs/utilities/signature/yParityToV',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/signature/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/signature/types',
            },
          ],
        },
        {
          text: 'SignatureErc6492',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/signatureerc6492',
            },
            {
              text: 'assert',
              link: '/docs/utilities/signatureerc6492/assert',
            },
            {
              text: 'from',
              link: '/docs/utilities/signatureerc6492/from',
            },
            {
              text: 'unwrap',
              link: '/docs/utilities/signatureerc6492/unwrap',
            },
            {
              text: 'validate',
              link: '/docs/utilities/signatureerc6492/validate',
            },
            {
              text: 'wrap',
              link: '/docs/utilities/signatureerc6492/wrap',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/signatureerc6492/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/signatureerc6492/types',
            },
          ],
        },
        {
          text: 'SignatureErc8010',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/signatureerc8010',
            },
            {
              text: 'assert',
              link: '/docs/utilities/signatureerc8010/assert',
            },
            {
              text: 'from',
              link: '/docs/utilities/signatureerc8010/from',
            },
            {
              text: 'unwrap',
              link: '/docs/utilities/signatureerc8010/unwrap',
            },
            {
              text: 'validate',
              link: '/docs/utilities/signatureerc8010/validate',
            },
            {
              text: 'wrap',
              link: '/docs/utilities/signatureerc8010/wrap',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/signatureerc8010/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/signatureerc8010/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Log',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/log',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/log/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/log/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/log/types',
        },
      ],
    },
    {
      text: 'Providers (EIP-1193)',
      collapsed: true,
      items: [
        {
          text: 'Provider',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/provider',
            },
            {
              text: 'from',
              link: '/docs/utilities/provider/from',
            },
            {
              text: 'createEmitter',
              link: '/docs/utilities/provider/createEmitter',
            },
            {
              text: 'parseError',
              link: '/docs/utilities/provider/parseError',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/provider/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/provider/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Signed & Typed Data',
      collapsed: true,
      items: [
        {
          text: 'PersonalMessage',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/personalmessage',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/personalmessage/getSignPayload',
            },
            {
              text: 'encode',
              link: '/docs/utilities/personalmessage/encode',
            },
            {
              text: 'recoverAddress',
              link: '/docs/utilities/personalmessage/recoverAddress',
            },
            {
              text: 'verify',
              link: '/docs/utilities/personalmessage/verify',
            },
          ],
        },
        {
          text: 'TypedData',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/typeddata',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/typeddata/getSignPayload',
            },
            {
              text: 'assert',
              link: '/docs/utilities/typeddata/assert',
            },
            {
              text: 'domainSeparator',
              link: '/docs/utilities/typeddata/domainSeparator',
            },
            {
              text: 'encode',
              link: '/docs/utilities/typeddata/encode',
            },
            {
              text: 'encodeType',
              link: '/docs/utilities/typeddata/encodeType',
            },
            {
              text: 'extractEip712DomainTypes',
              link: '/docs/utilities/typeddata/extractEip712DomainTypes',
            },
            {
              text: 'hashDomain',
              link: '/docs/utilities/typeddata/hashDomain',
            },
            {
              text: 'hashStruct',
              link: '/docs/utilities/typeddata/hashStruct',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/typeddata/serialize',
            },
            {
              text: 'validate',
              link: '/docs/utilities/typeddata/validate',
            },
            {
              text: 'recoverAddress',
              link: '/docs/utilities/typeddata/recoverAddress',
            },
            {
              text: 'verify',
              link: '/docs/utilities/typeddata/verify',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/typeddata/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/typeddata/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Siwe (Sign-in with Ethereum)',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/siwe',
        },
        {
          text: 'createMessage',
          link: '/docs/utilities/siwe/createMessage',
        },
        {
          text: 'generateNonce',
          link: '/docs/utilities/siwe/generateNonce',
        },
        {
          text: 'parseMessage',
          link: '/docs/utilities/siwe/parseMessage',
        },
        {
          text: 'validateMessage',
          link: '/docs/utilities/siwe/validateMessage',
        },
        {
          text: 'isUri',
          link: '/docs/utilities/siwe/isUri',
        },
        {
          text: 'Errors',
          link: '/docs/utilities/siwe/errors',
        },
        {
          text: 'Types',
          link: '/docs/utilities/siwe/types',
        },
      ],
    },
    {
      text: 'State Overrides',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/stateoverrides',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/stateoverrides/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/stateoverrides/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/stateoverrides/types',
        },
      ],
    },
    {
      text: 'Transaction',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/transaction',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/transaction/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/transaction/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/transaction/types',
        },
      ],
    },
    {
      text: 'Transaction Envelopes',
      collapsed: true,
      items: [
        {
          text: 'TxEnvelope',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelope',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelope/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelope/deserialize',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelope/from',
            },
            {
              text: 'getSerializedType',
              link: '/docs/utilities/txenvelope/getSerializedType',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelope/getSignPayload',
            },
            {
              text: 'getType',
              link: '/docs/utilities/txenvelope/getType',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelope/hash',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelope/serialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelope/toRpc',
            },
            {
              text: 'toTransactionRequest',
              link: '/docs/utilities/txenvelope/toTransactionRequest',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelope/validate',
            },
            {
              text: 'recoverAddress',
              link: '/docs/utilities/txenvelope/recoverAddress',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/txenvelope/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelope/types',
            },
          ],
        },
        {
          text: 'TxEnvelopeEip1559',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelopeeip1559',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelopeeip1559/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelopeeip1559/getSignPayload',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelopeeip1559/serialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelopeeip1559/toRpc',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelopeeip1559/hash',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelopeeip1559/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelopeeip1559/deserialize',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelopeeip1559/validate',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelopeeip1559/types',
            },
          ],
        },
        {
          text: 'TxEnvelopeEip2930',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelopeeip2930',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelopeeip2930/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelopeeip2930/getSignPayload',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelopeeip2930/serialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelopeeip2930/toRpc',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelopeeip2930/hash',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelopeeip2930/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelopeeip2930/deserialize',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelopeeip2930/validate',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelopeeip2930/types',
            },
          ],
        },
        {
          text: 'TxEnvelopeEip4844',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelopeeip4844',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelopeeip4844/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelopeeip4844/getSignPayload',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelopeeip4844/serialize',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelopeeip4844/hash',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelopeeip4844/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelopeeip4844/deserialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelopeeip4844/toRpc',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelopeeip4844/validate',
            },
            {
              text: 'Errors',
              link: '/docs/utilities/txenvelopeeip4844/errors',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelopeeip4844/types',
            },
          ],
        },
        {
          text: 'TxEnvelopeEip7702',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelopeeip7702',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelopeeip7702/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelopeeip7702/getSignPayload',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelopeeip7702/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelopeeip7702/deserialize',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelopeeip7702/hash',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelopeeip7702/serialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelopeeip7702/toRpc',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelopeeip7702/validate',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelopeeip7702/types',
            },
          ],
        },
        {
          text: 'TxEnvelopeLegacy',
          collapsed: true,
          items: [
            {
              text: 'Overview',
              link: '/docs/utilities/txenvelopelegacy',
            },
            {
              text: 'from',
              link: '/docs/utilities/txenvelopelegacy/from',
            },
            {
              text: 'getSignPayload',
              link: '/docs/utilities/txenvelopelegacy/getSignPayload',
            },
            {
              text: 'serialize',
              link: '/docs/utilities/txenvelopelegacy/serialize',
            },
            {
              text: 'toRpc',
              link: '/docs/utilities/txenvelopelegacy/toRpc',
            },
            {
              text: 'hash',
              link: '/docs/utilities/txenvelopelegacy/hash',
            },
            {
              text: 'assert',
              link: '/docs/utilities/txenvelopelegacy/assert',
            },
            {
              text: 'deserialize',
              link: '/docs/utilities/txenvelopelegacy/deserialize',
            },
            {
              text: 'validate',
              link: '/docs/utilities/txenvelopelegacy/validate',
            },
            {
              text: 'Types',
              link: '/docs/utilities/txenvelopelegacy/types',
            },
          ],
        },
      ],
    },
    {
      text: 'Transaction Receipt',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/transactionreceipt',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/transactionreceipt/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/transactionreceipt/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/transactionreceipt/types',
        },
      ],
    },
    {
      text: 'Transaction Request',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/transactionrequest',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/transactionrequest/fromRpc',
        },
        {
          text: 'toEnvelope',
          link: '/docs/utilities/transactionrequest/toEnvelope',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/transactionrequest/toRpc',
        },
        {
          text: 'Errors',
          link: '/docs/utilities/transactionrequest/errors',
        },
        {
          text: 'Types',
          link: '/docs/utilities/transactionrequest/types',
        },
      ],
    },
    {
      text: 'Withdrawal',
      collapsed: true,
      items: [
        {
          text: 'Overview',
          link: '/docs/utilities/withdrawal',
        },
        {
          text: 'fromRpc',
          link: '/docs/utilities/withdrawal/fromRpc',
        },
        {
          text: 'toRpc',
          link: '/docs/utilities/withdrawal/toRpc',
        },
        {
          text: 'Types',
          link: '/docs/utilities/withdrawal/types',
        },
      ],
    },
  ],
} satisfies SidebarItem
