[profile.default]
src = "test"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin/",
  "@account-abstraction/=lib/account-abstraction/",
  "account-abstraction/=lib/account-abstraction/contracts/",
  "account-abstraction-v07/=lib/account-abstraction-v07/contracts/",
  "solady/=lib/solady/src/",
  "solady-dc09481/=lib/solady-dc09481/src/",
  "solady-6c2d0da/=lib/solady-6c2d0da/src/"
]
