[profile.default]
src = "test"
out = "out"
libs = []
allow_paths = ["../node_modules"]
remappings = [
  "@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/",
  "account-abstraction/=../node_modules/account-abstraction-v08/",
  "account-abstraction-v07/=../node_modules/account-abstraction-v07/",
  "solady-dc09481/=../node_modules/solady-v153/src/",
  "solady-6c2d0da/=../node_modules/solady-v288/src/",
]
