import { parseAbi } from 'abitype'

export const zoneFactory = [
  {
    type: 'event',
    name: 'ZoneCreated',
    inputs: [
      { name: 'zoneId', type: 'uint32', indexed: true },
      { name: 'portal', type: 'address', indexed: true },
      { name: 'initialToken', type: 'address', indexed: false },
      { name: 'accessMode', type: 'bool', indexed: false },
      { name: 'gatewayMode', type: 'bool', indexed: false },
      { name: 'admin', type: 'address', indexed: false },
      { name: 'sequencers', type: 'address[]', indexed: false },
      { name: 'threshold', type: 'uint8', indexed: false },
      { name: 'verifier', type: 'address', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ZoneCreated',
    inputs: [
      { name: 'zoneId', type: 'uint32', indexed: true },
      { name: 'portal', type: 'address', indexed: true },
      { name: 'messenger', type: 'address', indexed: true },
      { name: 'initialToken', type: 'address', indexed: false },
      { name: 'admin', type: 'address', indexed: false },
      { name: 'sequencer', type: 'address', indexed: false },
      { name: 'verifier', type: 'address', indexed: false },
      { name: 'genesisBlockHash', type: 'bytes32', indexed: false },
      { name: 'genesisTempoBlockHash', type: 'bytes32', indexed: false },
      {
        name: 'genesisTempoBlockNumber',
        type: 'uint64',
        indexed: false,
      },
    ],
  },
  {
    type: 'function',
    name: 'createZone',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'initialToken', type: 'address' },
          { name: 'accessMode', type: 'bool' },
          { name: 'gatewayMode', type: 'bool' },
          { name: 'allowedAccounts', type: 'address[]' },
          { name: 'zoneGateways', type: 'address[]' },
          { name: 'admin', type: 'address' },
          { name: 'sequencers', type: 'address[]' },
          { name: 'threshold', type: 'uint8' },
          { name: 'rpcUrl', type: 'string' },
        ],
      },
    ],
    outputs: [
      { name: 'zoneId', type: 'uint32' },
      { name: 'portal', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'createZone',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'initialToken', type: 'address' },
          { name: 'admin', type: 'address' },
          { name: 'sequencer', type: 'address' },
          { name: 'verifier', type: 'address' },
          {
            name: 'zoneParams',
            type: 'tuple',
            components: [
              { name: 'genesisBlockHash', type: 'bytes32' },
              { name: 'genesisTempoBlockHash', type: 'bytes32' },
              { name: 'genesisTempoBlockNumber', type: 'uint64' },
            ],
          },
          { name: 'rpcUrl', type: 'string' },
        ],
      },
    ],
    outputs: [
      { name: 'zoneId', type: 'uint32' },
      { name: 'portal', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'nextZoneId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'zones',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint32' }],
    outputs: [
      {
        name: 'info',
        type: 'tuple',
        components: [
          { name: 'zoneId', type: 'uint32' },
          { name: 'portal', type: 'address' },
          { name: 'accessMode', type: 'bool' },
          { name: 'gatewayMode', type: 'bool' },
          { name: 'admin', type: 'address' },
          { name: 'sequencers', type: 'address[]' },
          { name: 'threshold', type: 'uint8' },
          { name: 'verifier', type: 'address' },
          { name: 'rpcUrl', type: 'string' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'verifier',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  ...parseAbi([
    'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
    'function transferOwnership(address newOwner)',
    'function isZonePortal(address portal) view returns (bool isPortal)',
    'error InvalidToken()',
    'error NotOwner()',
    'error InvalidAdmin()',
    'error InvalidSequencerSet()',
    'error InvalidClosedLoopConfig()',
    'error DuplicateAllowedAccount()',
    'error DuplicateZoneGateway()',
  ]),
] as const

const zonePortalCurrent = parseAbi([
  'event BatchSubmitted(uint64 indexed withdrawalBatchIndex, uint256 indexed withdrawalQueueIndex, bytes32 nextProcessedDepositQueueHash, bytes32 nextBlockHash, bytes32 withdrawalQueueHash, uint64 lastProcessedDepositNumber)',
  'event WithdrawalBounceBack(bytes32 indexed newCurrentDepositQueueHash, uint64 indexed fallbackNonce, address token, uint128 amount, uint64 depositNumber)',
  'event AdminTransferStarted(address indexed currentAdmin, address indexed pendingAdmin)',
  'event AdminTransferred(address indexed previousAdmin, address indexed newAdmin)',
  'event DepositMade(bytes32 indexed newCurrentDepositQueueHash, address indexed sender, address token, uint128 netAmount, uint128 fee, uint256 keyIndex, bytes32 ephemeralPubkeyX, uint8 ephemeralPubkeyYParity, bytes ciphertext, bytes12 nonce, bytes16 tag, address tempoRefundRecipient, uint64 depositNumber)',
  'event DepositBounceBack(address indexed tempoRefundRecipient, address token, uint128 amount, uint128 bouncebackFee)',
  'event DepositBounceBackPending(address indexed tempoRefundRecipient, address token, uint128 amount, uint128 bouncebackFee)',
  'event RefundClaimed(address indexed recipient, address indexed token, uint128 amount)',
  'event SequencerEncryptionKeyUpdated(bytes32 x, uint8 yParity, address pubkey, uint256 keyIndex, uint64 activationBlock)',
  'event ZoneGasRateUpdated(uint128 zoneGasRate)',
  'event MaxTempoGasRateUpdated(uint128 maxTempoGasRate)',
  'event BouncebackGasUpdated(uint64 bouncebackGas)',
  'event TokenEnabled(address indexed token, string name, string symbol, string currency)',
  'event DepositsPaused(address indexed token)',
  'event DepositsResumed(address indexed token)',
  'event PortalPaused(address indexed account)',
  'event PortalResumed(address indexed account)',
  'event AbdicationScheduled(uint8 indexed capability, uint64 effectiveAt)',
  'event RpcUrlUpdated(string rpcUrl)',
  'event SequencerSetUpdated(uint64 indexed nonce, uint8 threshold, address[] sequencers)',
  'event LeaderUpdated(address indexed previousLeader, address indexed newLeader, uint64 indexed epoch, uint64 activationTempoBlock)',
  'event EnforcementModesUpdated(bool accessMode, bool gatewayMode)',
  'event RoleUpdated(address indexed account, uint8 prev, uint8 next)',
  'function submitBatch(uint64 tempoBlockNumber, uint64 recentTempoBlockNumber, (bytes32 prevBlockHash, bytes32 nextBlockHash) blockTransition, (bytes32 prevProcessedHash, bytes32 nextProcessedHash, uint64 prevDepositNumber, uint64 nextDepositNumber) depositQueueTransition, bytes32 withdrawalQueueHash, bytes verifierConfig, bytes proof, uint256 zoneHeight, bytes[] signatures)',
])

export const zonePortal = [
  ...zonePortalCurrent,
  {
    name: 'WithdrawalProcessed',
    type: 'event',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'senderTag', type: 'bytes32', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint128', indexed: false },
      { name: 'callbackSuccess', type: 'bool', indexed: false },
    ],
  },
  {
    name: 'deposit',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_token', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint128' },
      { name: 'memo', type: 'bytes32' },
      { name: 'tempoRefundRecipient', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'depositEncrypted',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint128' },
      { name: 'keyIndex', type: 'uint256' },
      {
        name: 'encrypted',
        type: 'tuple',
        components: [
          { name: 'ephemeralPubkeyX', type: 'bytes32' },
          { name: 'ephemeralPubkeyYParity', type: 'uint8' },
          { name: 'ciphertext', type: 'bytes' },
          { name: 'nonce', type: 'bytes12' },
          { name: 'tag', type: 'bytes16' },
        ],
      },
      { name: 'tempoRefundRecipient', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'messenger',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'verifier',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'admin',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'pendingAdmin',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'paused',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'pauseExpiry',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    name: 'hasRole',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'expected', type: 'uint8' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'abdicationEffectiveAt',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'capability', type: 'uint8' }],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    name: 'pause',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'sequencerSetVersion',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    name: 'sequencerThreshold',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    name: 'sequencerCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'sequencerAt',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'enabledTokenCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'enabledTokenAt',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'tokenConfig',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [
      {
        name: 'config',
        type: 'tuple',
        components: [
          { name: 'enabled', type: 'bool' },
          { name: 'depositsActive', type: 'bool' },
        ],
      },
    ],
  },
  {
    name: 'sequencerEncryptionKey',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'x', type: 'bytes32' },
      { name: 'yParity', type: 'uint8' },
    ],
  },
  {
    name: 'encryptionKeyCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const

export const zoneMessenger = parseAbi([
  'function relayMessage(uint32 zoneId, address token, bytes32 senderTag, address target, uint128 amount, uint64 gasLimit, bytes data)',
])

export const zoneVerifier = parseAbi([
  'function verify(uint32 zoneId, uint64 tempoBlockNumber, uint64 anchorBlockNumber, bytes32 anchorBlockHash, uint64 expectedWithdrawalBatchIndex, (bytes32 prevBlockHash, bytes32 nextBlockHash) blockTransition, (bytes32 prevProcessedHash, bytes32 nextProcessedHash, uint64 prevDepositNumber, uint64 nextDepositNumber) depositQueueTransition, bytes32 withdrawalQueueHash, bytes verifierConfig, bytes proof) view returns (bool)',
])

export const zoneOutbox = [
  {
    name: 'WithdrawalRequested',
    type: 'event',
    inputs: [
      { name: 'withdrawalIndex', type: 'uint64', indexed: true },
      { name: 'sender', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'to', type: 'address', indexed: false },
      { name: 'amount', type: 'uint128', indexed: false },
      { name: 'fee', type: 'uint128', indexed: false },
      { name: 'memo', type: 'bytes32', indexed: false },
      { name: 'gasLimit', type: 'uint64', indexed: false },
      { name: 'fallbackNonce', type: 'uint64', indexed: false },
      { name: 'data', type: 'bytes', indexed: false },
      { name: 'revealTo', type: 'bytes', indexed: false },
    ],
  },
  {
    name: 'requestWithdrawal',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint128' },
      { name: 'memo', type: 'bytes32' },
      { name: 'gasLimit', type: 'uint64' },
      { name: 'fallbackRecipient', type: 'address' },
      { name: 'data', type: 'bytes' },
      { name: 'revealTo', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    name: 'calculateWithdrawalFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'gasLimit', type: 'uint64' }],
    outputs: [{ name: 'fee', type: 'uint128' }],
  },
] as const
