export {
  addChain,
  getAddresses,
  getPermissions,
  requestAddresses,
  requestPermissions,
  sendTransaction,
  signMessage,
  signTypedData,
  switchChain,
  verifyMessage,
  watchAsset,
} from './actions/wallet'
export type {
  AddChainParameters,
  FormattedTransactionRequest,
  GetPermissionsReturnType,
  GetAddressesReturnType,
  RequestAddressesReturnType,
  RequestPermissionsReturnType,
  SendTransactionParameters,
  SendTransactionReturnType,
  SignMessageParameters,
  SignMessageReturnType,
  SignTypedDataParameters,
  SignTypedDataReturnType,
  SwitchChainParameters,
  VerifyMessageParameters,
  VerifyMessageReturnType,
  WatchAssetParameters,
  WatchAssetReturnType,
} from './actions/wallet'
