name: Prepublish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Prepublish
        run: |
          cd src && pnpm version prerelease --preid $(git rev-parse --short=7 HEAD) && cd ..
          pnpm changeset:prepublish
          pnpx pkg-pr-new publish --pnpm --compact './src'